version: '3.5'

services:
  service_rss_feed:
    image: ace149/service_rss_feed
    restart: always 
    ports:
      - "8000:8000"
  
  redis:
    build: ./redis
    restart: always 
    expose:
      - "6379"