application:
    port: 8000
    host: 127.0.0.1 
database:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "password"
    database_name: "rss"
redis:
    host: "localhost"
    port: 6379